sudo: false
language: go
go:
  - 1.10.x
install:
  - nvm install
  - npm install -g source-map-support
  - go get -u github.com/gopherjs/gopherjs
  - npm install --global node-gyp

before_script:
  - export NODE_PATH="/usr/local/lib/node_modules"

  # Set up system calls for gopherjs test (nodejs).
  # https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md
  - cd $GOPATH/src/github.com/gopherjs/gopherjs/node-syscall/
  - node-gyp rebuild
  - mkdir -p ~/.node_libraries/
  - cp build/Release/syscall.node ~/.node_libraries/syscall.node
  - cd $TRAVIS_BUILD_DIR

script:
  - make test